apiVersion: apps/v1
kind: Deployment
metadata:
  name: vatcalc
  labels:
    app: vatcalc
spec:
  replicas: 5
  selector:
    matchLabels:
      app: vatcalc
      
  template:
    metadata:
      labels:
        app: vatcalc
        tier: vatcalc
    spec:
      automountServiceAccountToken: false
      containers:
        - name: vatcalc
          image: pmwtraining/vat-calc:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "8Mi"
              cpu: "50m"
              ephemeral-storage: "2Gi"
            limits:
              memory: "16Mi"
              cpu: "100m"
              ephemeral-storage: "4Gi"
          ports:
          - containerPort: 80
            name: vatcalc
            
---
apiVersion: v1
kind: Service
metadata:
  name: vatcalc
  labels:
    app: vatcalc
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: vatcalc
    tier: vatcalc
  type: LoadBalancer
